### PR TITLE
Subprompt

### PR DESCRIPTION
**Pull request by SebastienBruckert**
Creation of subprompt for all situations. Should be stable. Add of heredoc too

### CODE REVIEW

**Review by cgaspart — COMMENTED** [review]
Heredoc bug:

%> cat <<EOF>test.txt
heredoc> Salut
Heredoc> EOF
cat: stdin: Bad File descriptor

**Comment by SebastienBruckert** [comment]
This problem is fixed in the other branch with redirections. That's why we need to merge ;)
Didn't say it before, my bad !

**Review by jjaniec — APPROVED** [review]

**Review by Gamouche — APPROVED** [review]

**Review by cgaspart — APPROVED** [review]
Good

**Comment by Gamouche** [comment]
> la branche stable
<sub>[View in Slack](https://42born2code.slack.com/archives/GCCTUBRL7/p1535655867000200)</sub>

**Pull request merged**
