### PR TITLE
Subprompt

### PR DESCRIPTION
**Pull request by jjaniec**

### CODE REVIEW

**Comment by SebastienBruckert** [comment]
On line edition, on Ubuntu 16 : 
-> Backspace key make weird stuff, don't know if it's corrected in the new line_edition

Still on Ubuntu 16, all heredocs strings fail because sh on ubuntu doesn't understand <<<

Seems to be good, need more tests

**Review by SebastienBruckert — APPROVED** [review]
Good to me except for leaks !

**Comment by jjaniec** [comment]
Allons y parlons anglais

His branch has not been merged for the last month so I guess he maybe fixed it  `¯\_(ツ)_/¯`

Oh that's why tests failed, what are we doing then, running tests w/ "<<<" in test string with `bash -c` when testing on linux ? or do we skip TK_TLESS token tests on linux as we're imitating sh ?

**Comment by SebastienBruckert** [comment]
We should just run without since we're not doing a very big cross compil program. Else, we would install / find a shell which work as we want it to work and make our test with it.

BTW, I'm branching on this commit to start shell script

**Pull request merged**
